/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simuladordememoria;

import java.awt.Dimension;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Vector;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author LENOVO
 */
public class Ventana2 extends javax.swing.JFrame {

    public int memTotal;
    public int tiempoMin;
    public int tiempoMax;
    public int ajuste;
    public LinkedList<Particion> particiones;
    public int particionMayor;
    public LinkedList<Proceso> listaProcesos;
    public LinkedList<Proceso> procesosEjecutando;
    public boolean simIniciada;
    public Hilo hiloAjustes;

    ModeloV2 model;

    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
    }

    public Ventana2(int memTotal, int tiempoMin, int tiempoMax, int ajuste, LinkedList<Particion> part) {
        initComponents();
        this.memTotal = memTotal;
        this.tiempoMin = tiempoMin;
        this.tiempoMax = tiempoMax;
        this.ajuste = ajuste;
        this.particiones = part;
        this.particionMayor = this.obtenerParticionMayor();
    }
    
    private int obtenerParticionMayor() {
        int mayor = 0;
        for (Particion particion : this.particiones) {
            if (particion.getTamanio() >= mayor) {
                mayor = particion.getTamanio();
            }
        }
        System.out.println("Particion mayor: " + mayor);
        return mayor;
    }

    public void aniadirPaneles(LinkedList<Particion> particiones) {
        contenedorParticiones.removeAll();
        contenedorParticiones2.removeAll();

        for (int i=0; i<particiones.size(); i++) {
            PanelParticion panel = new PanelParticion();
            panel.setTexto("", "", "", "", "");
            panel.setEnUso(false);
            if (i < particiones.size()/2) {
                contenedorParticiones.add(panel);
                contenedorParticiones.add(Box.createRigidArea(new Dimension(5, 10)));
            } else {
                contenedorParticiones2.add(panel);
                contenedorParticiones2.add(Box.createRigidArea(new Dimension(5, 10)));
            }
            particiones.get(i).setPanel(panel);

        }
        contenedorParticiones.revalidate();
        contenedorParticiones.repaint();
        contenedorParticiones2.revalidate();
        contenedorParticiones2.repaint();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevo = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProcesos = new javax.swing.JTable();
        contenedorParticiones = new javax.swing.JPanel();
        contenedorParticiones2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnIniciar.setText("Iniciar Simulacion");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        tablaProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProcesos);

        contenedorParticiones.setLayout(new javax.swing.BoxLayout(contenedorParticiones, javax.swing.BoxLayout.LINE_AXIS));

        contenedorParticiones2.setLayout(new javax.swing.BoxLayout(contenedorParticiones2, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIniciar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
                    .addComponent(contenedorParticiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contenedorParticiones2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnIniciar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contenedorParticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(contenedorParticiones2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        model = new ModeloV2();
        tablaProcesos.setModel(model);

        model.addColumn(0);
        aniadirPaneles(this.particiones);
        this.listaProcesos = new LinkedList();

    
        hiloAjustes = new Hilo(listaProcesos, particiones, ajuste, model);
    }//GEN-LAST:event_formWindowOpened

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        Dialogo x = new Dialogo(this, true, this.particionMayor);
        x.setVisible(true);

        if (x.getRootPane() != null) {
            Vector v = new Vector();
            v.addElement(model.getRowCount() + 1);
            v.addElement(x.txtNombre.getText());
            v.addElement((int) (Math.random() * (this.tiempoMax - this.tiempoMin + 1) + this.tiempoMin));
            v.addElement(x.txtCantidad.getText());
            v.addElement(0);
            v.addElement(Float.parseFloat("0.00"));          

            model.addRow(v);
            listaProcesos.add(new Proceso(Integer.parseInt(v.elementAt(0).toString()) , v.elementAt(1).toString(), Integer.parseInt(v.elementAt(2).toString() ), Integer.parseInt(v.elementAt(3).toString()) ));
            
            
            if(simIniciada){
                listaProcesos.getLast().setEstado(2);
                model.setValueAt("En espera", listaProcesos.getLast().getId() - 1, 4);
               // hiloAjustes.addProceso(listaProcesos.getLast());
            }
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        if(this.simIniciada){
            JOptionPane.showMessageDialog(this, "La simulacion ya ha sido iniciada", "NOOOO", HEIGHT);
            return;
        }
        this.simIniciada = true;
        hiloAjustes.start();
        //iniciarTimerProcesos();
       // primerAjuste();
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JPanel contenedorParticiones;
    private javax.swing.JPanel contenedorParticiones2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProcesos;
    // End of variables declaration//GEN-END:variables
}
